# Generated by Django 6.0.7 on 2026-07-23 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HOUSING', 'Housing'), ('FOOD', 'Food'), ('TRANSPORT', 'Transport'), ('UTILITIES', 'Utilities'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('SHOPPING', 'Shopping'), ('SAVINGS', 'Savings'), ('OTHER', 'Other')], max_length=50)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
